language: php
dist: bionic
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo systemctl stop beanstalkd || true
  - sudo beanstalkd -l 127.0.0.1 -p 11301 &

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpdbg -qrr vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
