version: "3.8"
services:
  beanstalk:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-beanstalkd
  composer:
    image: composer:latest
    volumes:
      - ./composer.json:/app/composer.json
      - ./vendor:/app/vendor
    command: install --ignore-platform-reqs
  phpunit-ci:
    init: true
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-phpunit
    environment:
      SERVER_HOST: beanstalk
    depends_on:
      - beanstalk
    volumes:
      - ./:/app:ro
      - ./tests/coverage:/app/tests/coverage
    entrypoint: [
        "/app/vendor/bin/phpunit",
        "--do-not-cache-result",
        "--coverage-clover",
        "/app/tests/coverage/clover.xml"
    ]
  phpunit:
    init: true
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-phpunit
    environment:
      SERVER_HOST: beanstalk
    depends_on:
      - beanstalk
    volumes:
      - ./:/app:ro
      - ./tests/coverage:/app/tests/coverage:rw
    entrypoint: [
      "/app/vendor/bin/phpunit",
      "--do-not-cache-result",
      "--coverage-html",
      "/app/tests/coverage"
    ]
