version: "3.8"
services:
  beanstalk:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-beanstalkd
  composer:
    image: composer:latest
    volumes:
      - ./composer.json:/app/composer.json
      - ./vendor:/app/vendor
    command: install --ignore-platform-reqs
  composer-command: &cc
    init: true
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php
    volumes:
      - ./:/app:ro
    working_dir: "/app"

  phpstan:
    <<: *cc
    entrypoint: ["/app/vendor/bin/phpstan"]
  phpcs:
    <<: *cc
    entrypoint: [ "/app/vendor/bin/phpcs" ]
  phpunit:
    <<: *cc
    environment:
      SERVER_HOST: beanstalk
    depends_on:
      - beanstalk
    volumes:
      - ./:/app:ro
      - ./tests/coverage:/app/tests/coverage:rw
    entrypoint: ["/app/vendor/bin/phpunit"]
    command: [
        "--do-not-cache-result",
        "--coverage-html",
        "/app/tests/coverage"
    ]