name: "Tests"

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose run --rm composer
      - run: docker-compose run --rm phpunit
      - uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: "--format=php-clover tests/coverage/clover.xml"